# Generated by Django 5.0.1 on 2024-02-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField()),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.manager')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
